In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import joblib 
import seaborn as sns 
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix,classification_report

In [2]:
df=pd.read_csv("amazon_musical_instruments_reviews.csv")

In [3]:
df.head()

reviewerID        asin  \
0  A2IBPI20UZIR0U  1384719342   
1  A14VAT5EAX3D9S  1384719342   
2  A195EZSQDW3E21  1384719342   
3  A2C00NNG1ZQQG2  1384719342   
4   A94QU4C90B1AX  1384719342   

                                       reviewerName   helpful  \
0  cassandra tu "Yeah, well, that's just like, u...    [0, 0]   
1                                              Jake  [13, 14]   
2                     Rick Bennette "Rick Bennette"    [1, 1]   
3                         RustyBill "Sunday Rocker"    [0, 0]   
4                                     SEAN MASLANKA    [0, 0]   

                                          reviewText  overall  \
0  Not much to write about here, but it does exac...      5.0   
1  The product does exactly as it should and is q...      5.0   
2  The primary job of this device is to block the...      5.0   
3  Nice windscreen protects my MXL mic and preven...      5.0   
4  This pop filter is great. It looks and perform...      5.0   

                                 summary  unixReviewTime   reviewTime  
0                                   good      1393545600  02 28, 2014  
1                                   Jake      1363392000  03 16, 2013  
2                   It Does The Job Well      1377648000  08 28, 2013  
3          GOOD WINDSCREEN FOR THE MONEY      1392336000  02 14, 2014  
4  No more pops when I record my vocals.      1392940800  02 21, 2014

In [4]:
df=pd.DataFrame(df)

In [5]:
df['overall'].value_counts()

overall
5.0    6938
4.0    2084
3.0     772
2.0     250
1.0     217
Name: count, dtype: int64

In [6]:
df.isna().sum()

reviewerID         0
asin               0
reviewerName      27
helpful            0
reviewText         7
overall            0
summary            0
unixReviewTime     0
reviewTime         0
dtype: int64

In [7]:
df = df.dropna(subset=['reviewerName'])


In [8]:
df=df.dropna(subset=['reviewText'])

In [9]:
df.isna().sum()

reviewerID        0
asin              0
reviewerName      0
helpful           0
reviewText        0
overall           0
summary           0
unixReviewTime    0
reviewTime        0
dtype: int64

In [10]:
x=df['reviewText']
y=df['overall']


vectorizer=CountVectorizer()
x=vectorizer.fit_transform(x)

joblib.dump(vectorizer,"vectorizerforreview.pkl")

['vectorizerforreview.pkl']

In [11]:
#Balancing imbalanced dataset
from imblearn.over_sampling import SMOTE

smote=SMOTE()

x,y=smote.fit_resample(x,y)

In [12]:
y.value_counts()

overall
5.0    6912
3.0    6912
4.0    6912
2.0    6912
1.0    6912
Name: count, dtype: int64

In [13]:
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=42)


In [14]:
model=MLPClassifier(hidden_layer_sizes=(100,),solver='lbfgs')
model.fit(X_train,y_train)

y_pred=model.predict(X_test)
print(y_pred)

joblib.dump(model,"modelforperceptron.pkl")


[2. 2. 3. ... 1. 2. 5.]


d:\TechAxis\week56\venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:546: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)


['modelforperceptron.pkl']

In [15]:
print("\nconfusion_matrix: \n",confusion_matrix(y_test,y_pred))

#Detailed classification report 
print("\nClassification Report: ")
print(classification_report(y_test,y_pred))


confusion_matrix: 
 [[1597   43   61   32   10]
 [  33 1512   90   68   16]
 [  71  128 1270  179   65]
 [  61  129  233 1017  299]
 [  15   20   75  241 1375]]

Classification Report: 
              precision    recall  f1-score   support

         1.0       0.90      0.92      0.91      1743
         2.0       0.83      0.88      0.85      1719
         3.0       0.73      0.74      0.74      1713
         4.0       0.66      0.58      0.62      1739
         5.0       0.78      0.80      0.79      1726

    accuracy                           0.78      8640
   macro avg       0.78      0.78      0.78      8640
weighted avg       0.78      0.78      0.78      8640

