In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import joblib 
import seaborn as sns 
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix,classification_report

In [2]:
df=pd.read_csv("amazon_musical_instruments_reviews.csv")

In [3]:
df=pd.DataFrame(df)

In [4]:
df = df.dropna(subset=['reviewerName'])
df=df.dropna(subset=['reviewText'])

In [5]:
def f(row):
   
    if row['overall'] == 3.0:
        val = 'Neutral'

    elif row['overall'] == 1.0 or row['overall'] == 2.0:
        val = 'Negative'

    elif row['overall'] == 4.0 or row['overall'] == 5.0:
        val = 'Positive'

    else:
        val = -1

    return val

df['overall'] = df.apply(f, axis=1)
df.head(2)

reviewerID        asin  \
0  A2IBPI20UZIR0U  1384719342   
1  A14VAT5EAX3D9S  1384719342   

                                       reviewerName   helpful  \
0  cassandra tu "Yeah, well, that's just like, u...    [0, 0]   
1                                              Jake  [13, 14]   

                                          reviewText   overall summary  \
0  Not much to write about here, but it does exac...  Positive    good   
1  The product does exactly as it should and is q...  Positive    Jake   

   unixReviewTime   reviewTime  
0      1393545600  02 28, 2014  
1      1363392000  03 16, 2013

In [6]:
df['reviews'] = df['summary'] + ' ' + df['reviewText']

In [7]:
df.head(2)

reviewerID        asin  \
0  A2IBPI20UZIR0U  1384719342   
1  A14VAT5EAX3D9S  1384719342   

                                       reviewerName   helpful  \
0  cassandra tu "Yeah, well, that's just like, u...    [0, 0]   
1                                              Jake  [13, 14]   

                                          reviewText   overall summary  \
0  Not much to write about here, but it does exac...  Positive    good   
1  The product does exactly as it should and is q...  Positive    Jake   

   unixReviewTime   reviewTime  \
0      1393545600  02 28, 2014   
1      1363392000  03 16, 2013   

                                             reviews  
0  good Not much to write about here, but it does...  
1  Jake The product does exactly as it should and...

In [8]:
x=df['reviews']
y=df['overall']


vectorizer=CountVectorizer()
x=vectorizer.fit_transform(x)

joblib.dump(vectorizer,"newvectorizerforreview.pkl")

['newvectorizerforreview.pkl']

In [9]:
from imblearn.over_sampling import SMOTE

smote=SMOTE()

x,y=smote.fit_resample(x,y)

In [10]:
y.value_counts()

overall
Positive    8991
Neutral     8991
Negative    8991
Name: count, dtype: int64

In [11]:
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=42)


In [12]:
model=MLPClassifier(hidden_layer_sizes=(100,),solver='lbfgs')
model.fit(X_train,y_train)

y_pred=model.predict(X_test)
print(y_pred)

joblib.dump(model,"newmodelforperceptronafterfeatureengineering.pkl")


['Neutral' 'Neutral' 'Negative' ... 'Neutral' 'Neutral' 'Negative']


d:\TechAxis\week56\venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:546: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)


['newmodelforperceptronafterfeatureengineering.pkl']

In [13]:
print("\nconfusion_matrix: \n",confusion_matrix(y_test,y_pred))

#Detailed classification report 
print("\nClassification Report: ")
print(classification_report(y_test,y_pred))


confusion_matrix: 
 [[2133   63   52]
 [  53 2090  104]
 [  39  109 2101]]

Classification Report: 
              precision    recall  f1-score   support

    Negative       0.96      0.95      0.95      2248
     Neutral       0.92      0.93      0.93      2247
    Positive       0.93      0.93      0.93      2249

    accuracy                           0.94      6744
   macro avg       0.94      0.94      0.94      6744
weighted avg       0.94      0.94      0.94      6744

